# Site settings
title: Rodeo Blog
email: frew@cs.stanford.edu
description: > # this means to ignore newlines until "baseurl:"
  Taming the wild west of distributed systems.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.rodeo.io" # the base hostname & protocol for your site
twitter_username: fredwulff
github_username: frew

# Build settings
markdown: kramdown
